# Guard 08: LossOfContainment must be entailed ⊑ bfo:Process (BFO_0000015)
# Violation: LossOfContainment is NOT subClassOf* BFO_0000015
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX copi: <https://www.inf.ufrgs.br/ontologies/copi/>
PREFIX obo:  <http://purl.obolibrary.org/obo/>

SELECT ?x WHERE {
  BIND(copi:LossOfContainment AS ?x)
  ?x a owl:Class .
  FILTER NOT EXISTS {
    ?x rdfs:subClassOf* obo:BFO_0000015 .
  }
}
