# Guard 03: Valve must be entailed as subClassOf iof-constr:MaterialArtifact
# Violation: Valve is NOT a subClassOf* MaterialArtifact
PREFIX owl:       <http://www.w3.org/2002/07/owl#>
PREFIX rdfs:      <http://www.w3.org/2000/01/rdf-schema#>
PREFIX copi:      <https://www.inf.ufrgs.br/ontologies/copi/>
PREFIX iof-constr: <https://spec.industrialontologies.org/ontology/construct/>

SELECT ?x WHERE {
  BIND(copi:Valve AS ?x)
  ?x a owl:Class .
  FILTER NOT EXISTS {
    ?x rdfs:subClassOf* iof-constr:MaterialArtifact .
  }
}
