# Guard 05: Generic Valve must NOT be entailed as subClassOf iof-constr:Assembly
# (Valve has no hasComponentPartAtAllTimes axioms; AMB-1)
# Violation: Valve IS a subClassOf* Assembly
PREFIX owl:        <http://www.w3.org/2002/07/owl#>
PREFIX rdfs:       <http://www.w3.org/2000/01/rdf-schema#>
PREFIX copi:       <https://www.inf.ufrgs.br/ontologies/copi/>
PREFIX iof-constr: <https://spec.industrialontologies.org/ontology/construct/>

SELECT ?x WHERE {
  BIND(copi:COPI_0000077 AS ?x)
  ?x a owl:Class .
  ?x rdfs:subClassOf* iof-constr:Assembly .
}
